//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_mobile_recharge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallerTune
    {
        public int Tansaction_id { get; set; }
        public string Transaction_Name { get; set; }
        public string Type { get; set; }
        public string Account_No { get; set; }
        public string amount { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string TUNE_CODE { get; set; }
        public string TUNE_NAME { get; set; }
        public string CHARGES { get; set; }
        public string SINGER { get; set; }
        public string payment_method { get; set; }
    }
}
