//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_mobile_recharge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_deposit
    {
        public int ID { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual loginfo loginfo { get; set; }
    }
}
