//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_mobile_recharge.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class contactus
    {
        public int id { get; set; }
        [Required]
        public string Name { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string MESSAGES { get; set; }
        public string sender { get; set; }
        public string replay { get; set; }
    }
}
