//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_mobile_recharge.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class feedback
    {
        public int id { get; set; }
        [Required]
        public string username { get; set; }
        public string Email { get; set; }
        public string phone { get; set; }
        public string rating { get; set; }
        public string feedback1 { get; set; }
    
        public virtual feedback feedback11 { get; set; }
        public virtual feedback feedback2 { get; set; }
    }
}
