//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_mobile_recharge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class offers
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string Network { get; set; }
        public string Description_ { get; set; }
        public string Price { get; set; }
        public string Transaction_name { get; set; }
        public string Payment_Methods { get; set; }
        public string account_no { get; set; }
        public string amount { get; set; }
        public string Reciever_Mobile_No { get; set; }
    }
}
