//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_mobile_recharge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer
    {
        public int Transaction_id { get; set; }
        public string Transaction_Name { get; set; }
        public string Type { get; set; }
        public string Account_No { get; set; }
        public string mpin { get; set; }
        public string amount { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string offer_recharge_consumernumber { get; set; }
        public string paymentmethod { get; set; }
        public string @operator { get; set; }
        public string offercode { get; set; }
        public string offer_type { get; set; }
        public string offer_description { get; set; }
        public string offer_price { get; set; }
    }
}
