//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_mobile_recharge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roletable
    {
        public int RoleId { get; set; }
        public string user_id { get; set; }
        public string Role { get; set; }
    
        public virtual loginfo loginfo { get; set; }
    }
}
