//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_mobile_recharge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlogin
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string user_id { get; set; }
        public Nullable<int> balance { get; set; }
        public string Transaction_Name { get; set; }
        public string Type { get; set; }
        public string mpincheck { get; set; }
        public Nullable<int> amount { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string offer_recharge_consumer_numbers { get; set; }
        public string paymentmethod { get; set; }
        public string operators { get; set; }
        public string account_no { get; set; }
        public string mpin { get; set; }
    
        public virtual loginfo loginfo { get; set; }
    }
}
